"""Implement hybrid analytics model

Revision ID: 751096b43d03
Revises: cfc020cf54bb
Create Date: 2025-09-19 08:01:37.444733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751096b43d03'
down_revision: Union[str, Sequence[str], None] = 'cfc020cf54bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_logs', sa.Column('generated_task_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_logs', 'generated_task_details')
    # ### end Alembic commands ###
